//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MpMigrate.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("mssql")]
        public string dbtype {
            get {
                return ((string)(this["dbtype"]));
            }
            set {
                this["dbtype"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string pleskMySQLHost {
            get {
                return ((string)(this["pleskMySQLHost"]));
            }
            set {
                this["pleskMySQLHost"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MaestroPanelApiKey {
            get {
                return ((string)(this["MaestroPanelApiKey"]));
            }
            set {
                this["MaestroPanelApiKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("localhost")]
        public string MaestroPanelHost {
            get {
                return ((string)(this["MaestroPanelHost"]));
            }
            set {
                this["MaestroPanelHost"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9715")]
        public int MaestroPanelPort {
            get {
                return ((int)(this["MaestroPanelPort"]));
            }
            set {
                this["MaestroPanelPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("default")]
        public string domainPlanName {
            get {
                return ((string)(this["domainPlanName"]));
            }
            set {
                this["domainPlanName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string pleskResellerName {
            get {
                return ((string)(this["pleskResellerName"]));
            }
            set {
                this["pleskResellerName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool logging {
            get {
                return ((bool)(this["logging"]));
            }
            set {
                this["logging"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool importEmails {
            get {
                return ((bool)(this["importEmails"]));
            }
            set {
                this["importEmails"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool importDomains {
            get {
                return ((bool)(this["importDomains"]));
            }
            set {
                this["importDomains"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool importDatabases {
            get {
                return ((bool)(this["importDatabases"]));
            }
            set {
                this["importDatabases"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool importSubdomains {
            get {
                return ((bool)(this["importSubdomains"]));
            }
            set {
                this["importSubdomains"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool importDomainAlias {
            get {
                return ((bool)(this["importDomainAlias"]));
            }
            set {
                this["importDomainAlias"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CopyHttpFiles {
            get {
                return ((bool)(this["CopyHttpFiles"]));
            }
            set {
                this["CopyHttpFiles"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\inetpub\\vhosts\\{DOMAIN}\\httpdocs")]
        public string SourceDirPattern {
            get {
                return ((string)(this["SourceDirPattern"]));
            }
            set {
                this["SourceDirPattern"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\{DESTINATION}\\c$\\vhosts\\{DOMAIN}\\http")]
        public string DestinationDirPattern {
            get {
                return ((string)(this["DestinationDirPattern"]));
            }
            set {
                this["DestinationDirPattern"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("192.168.2.71")]
        public string DestinationServerIp {
            get {
                return ((string)(this["DestinationServerIp"]));
            }
            set {
                this["DestinationServerIp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DestinationServerPassword {
            get {
                return ((string)(this["DestinationServerPassword"]));
            }
            set {
                this["DestinationServerPassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Administrator")]
        public string DestinationServerUsername {
            get {
                return ((string)(this["DestinationServerUsername"]));
            }
            set {
                this["DestinationServerUsername"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Program Files (x86)\\Mail Enable\\Postoffices\\{DOMAIN}\\MAILROOT\\{MAILBOX}")]
        public string SourceDirEmailPattern {
            get {
                return ((string)(this["SourceDirEmailPattern"]));
            }
            set {
                this["SourceDirEmailPattern"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\{DESTINATION}\\c$\\Program Files (x86)\\Mail Enable\\Postoffices\\{DOMAIN}\\MAILROOT\\" +
            "{MAILBOX}")]
        public string DestinationDirEmailPatter {
            get {
                return ((string)(this["DestinationDirEmailPatter"]));
            }
            set {
                this["DestinationDirEmailPatter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CopyEmailFiles {
            get {
                return ((bool)(this["CopyEmailFiles"]));
            }
            set {
                this["CopyEmailFiles"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ImportReseller {
            get {
                return ((bool)(this["ImportReseller"]));
            }
            set {
                this["ImportReseller"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool exportDatabaseScript {
            get {
                return ((bool)(this["exportDatabaseScript"]));
            }
            set {
                this["exportDatabaseScript"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string mysqlHost {
            get {
                return ((string)(this["mysqlHost"]));
            }
            set {
                this["mysqlHost"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Packages")]
        public string DomainPackageLocalDir {
            get {
                return ((string)(this["DomainPackageLocalDir"]));
            }
            set {
                this["DomainPackageLocalDir"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CreateDomainPackage {
            get {
                return ((bool)(this["CreateDomainPackage"]));
            }
            set {
                this["CreateDomainPackage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\{DESTINATION}\\c$\\DomainPackages")]
        public string DomainPackageDestinationDir {
            get {
                return ((string)(this["DomainPackageDestinationDir"]));
            }
            set {
                this["DomainPackageDestinationDir"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool exportMySQL {
            get {
                return ((bool)(this["exportMySQL"]));
            }
            set {
                this["exportMySQL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool exportMsSQL {
            get {
                return ((bool)(this["exportMsSQL"]));
            }
            set {
                this["exportMsSQL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CopyDomainPackage {
            get {
                return ((bool)(this["CopyDomainPackage"]));
            }
            set {
                this["CopyDomainPackage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("admin")]
        public string mysqlUser {
            get {
                return ((string)(this["mysqlUser"]));
            }
            set {
                this["mysqlUser"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string mysqlPassword {
            get {
                return ((string)(this["mysqlPassword"]));
            }
            set {
                this["mysqlPassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3306")]
        public string mysqlPort {
            get {
                return ((string)(this["mysqlPort"]));
            }
            set {
                this["mysqlPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("admin")]
        public string pleskMySQLUser {
            get {
                return ((string)(this["pleskMySQLUser"]));
            }
            set {
                this["pleskMySQLUser"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string pleskMySQLPassword {
            get {
                return ((string)(this["pleskMySQLPassword"]));
            }
            set {
                this["pleskMySQLPassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8306")]
        public string pleskMySQLPort {
            get {
                return ((string)(this["pleskMySQLPort"]));
            }
            set {
                this["pleskMySQLPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Program Files (x86)\\Parallels\\Plesk\\admin\\db\\psa.mdb")]
        public string pleskMsAccessMdbPath {
            get {
                return ((string)(this["pleskMsAccessMdbPath"]));
            }
            set {
                this["pleskMsAccessMdbPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string entrenixMsAccessMdbPath {
            get {
                return ((string)(this["entrenixMsAccessMdbPath"]));
            }
            set {
                this["entrenixMsAccessMdbPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string pleskMsSqlHost {
            get {
                return ((string)(this["pleskMsSqlHost"]));
            }
            set {
                this["pleskMsSqlHost"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("admin")]
        public string pleskMsSqlUser {
            get {
                return ((string)(this["pleskMsSqlUser"]));
            }
            set {
                this["pleskMsSqlUser"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string pleskMsSqlPassword {
            get {
                return ((string)(this["pleskMsSqlPassword"]));
            }
            set {
                this["pleskMsSqlPassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MaestroPanelMsSqlHost {
            get {
                return ((string)(this["MaestroPanelMsSqlHost"]));
            }
            set {
                this["MaestroPanelMsSqlHost"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("sa")]
        public string MaestroPanelMsSqlUser {
            get {
                return ((string)(this["MaestroPanelMsSqlUser"]));
            }
            set {
                this["MaestroPanelMsSqlUser"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MaestroPanelMsSqlPassword {
            get {
                return ((string)(this["MaestroPanelMsSqlPassword"]));
            }
            set {
                this["MaestroPanelMsSqlPassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("mast")]
        public string MaestroPanelDatabaseName {
            get {
                return ((string)(this["MaestroPanelDatabaseName"]));
            }
            set {
                this["MaestroPanelDatabaseName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Program Files\\MaestroPanel\\Web\\data\\mast.sqlite")]
        public string MaestroPanelSQLitePath {
            get {
                return ((string)(this["MaestroPanelSQLitePath"]));
            }
            set {
                this["MaestroPanelSQLitePath"] = value;
            }
        }
    }
}
